spring.application.name=product
spring.datasource.url=jdbc:mysql://localhost:3306/db_name
spring.datasource.username=root
spring.datasource.password=rafa
spring.datasource.driverClassName=com.mysql.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

sever.address=0.0.0.0
server.port=8080


server.tomcat.max-http-header-size=65536